### ISSUE TITLE
interesting... 

### ISSUE THREAD

**Issue by LelandSindt** [BercziSandor/gmaps_tracker#1]
Am I correct that you are tracking a person's movement in relation to you? ---Have you found it to be useful?

I wanted a way to log my daughter's phone location history so we could find it after the battery dies... 
https://github.com/LelandSindt/locator

**Comment by BercziSandor** [comment]
Hi, we are on the same path - I have a daughter, as well. ;)
The project is only for fun, I don't wanted to make an app or so.
As you can see, it isn't dockerized yet, it is only about tracking.
Maybe I will make it possible to send alerts (messenger, email etc) if
 - some person moves permanently
 - is around me
 - is around some object (home, school, workplace etc)
 - is leaving (home, school, workplace etc)
 - etc
Maybe these two functions should be separated: one for tracking, one for monitoring/alerting.

What do you think, would it be useful?

**Comment by LelandSindt** [comment]
I am considering something similar, but any kind of alerting logic would consume locations from the adafruit.io feed. 

Because I am a fan of physical displays I may do something like https://github.com/gaussmeter/gaussmeter --- different colors for different locations, etc..

**Comment by BercziSandor** [comment]
Wow, congratulations.
Great work.

**Comment by BercziSandor** [comment]
I'll continue working on this project soon.

**Comment by LelandSindt** [comment]
I will keep an eye on it. :+1:
